Controllers/MedicamentoController.cs
using ControleMedicamentos.Filters;
using ControleMedicamentos.Helper;
using ControleMedicamentos.Models;
using ControleMedicamentos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleMedicamentos.Controllers;

[PaginaParaUsuarioLogado]
public class MedicamentoController : Controller
{
    private readonly IMedicamentoRepositorio _medicamentoRepositorio;
    private readonly ISessao _sessao;
    public MedicamentoController(IMedicamentoRepositorio medicamentoRepositorio, ISessao sessao)
    {
        _medicamentoRepositorio = medicamentoRepositorio;
        _sessao = sessao;
    }
    public IActionResult Index()
    {
        var usuarioLogado = _sessao.BuscarSessaoDoUsuario();
        var medicamentos = _medicamentoRepositorio.ListarTodos(usuarioLogado.Id);

        return View(medicamentos);
    }

    public IActionResult Criar()
    {
        return View();
    }

    public IActionResult Editar(int id)
    {
        var medicamento = _medicamentoRepositorio.ListarPorId(id);
        return View(medicamento);
    }

    public IActionResult ApagarConfirmacao(int id)
    {
        var medicamento = _medicamentoRepositorio.ListarPorId(id);

        return View(medicamento);
    }

    [HttpPost]
    public IActionResult Criar(MedicamentoModel medicamento)
    {
        try
        {
            if (!ModelState.IsValid)
            {
                return View(medicamento);
            }

            var usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            medicamento.UsuarioId = usuarioLogado.Id;

            _medicamentoRepositorio.Adicionar(medicamento);
            TempData["MensagemSucesso"] = "Medicamento cadastrado com sucesso.";
            return RedirectToAction("Index");
        }
        catch (Exception mensagem)
        {

            TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar o medicamento. Detalhes do erro: {mensagem.Message}";
            return RedirectToAction("Index");
        }
        
    }

    [HttpPost]
    public IActionResult Alterar(MedicamentoModel medicamento)
    {
        try
        {
            if (!ModelState.IsValid)
            {
                return View("Editar", medicamento);
            }
            var usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            medicamento.UsuarioId = usuarioLogado.Id;

            _medicamentoRepositorio.Atualizar(medicamento);
            TempData["MensagemSucesso"] = "Medicamento alterado com sucesso.";
            return RedirectToAction("Index");
        }
        catch (Exception mensagem)
        {

            TempData["MensagemErro"] = $"Ops, não conseguimos alterar o medicamento. Detalhes do erro: {mensagem.Message}";
            return RedirectToAction("Index");
        }
        
    }

    public IActionResult Apagar(int id)
    {
        try
        {
            bool apagado = _medicamentoRepositorio.Apagar(id);
            if (apagado)
            {
                TempData["MensagemSucesso"] = "Medicamento apagado com sucesso.";
            }
            else
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar o medicamento.";
            }
            
            return RedirectToAction("Index");
        }
        catch (Exception mensagem)
        {

            TempData["MensagemErro"] = $"Ops, não conseguimos apagar o medicamento. Detalhes do erro: {mensagem.Message}";
            return RedirectToAction("Index");
        }

        
    }
}

Views/Medicamento/ApagarConfirmacao.cshtml
@model MedicamentoModel

@{
    ViewData["Title"] = "Confirmação Apagar Medicamento";
}

<div class="text-center">
    <h3>Realmente deseja apagar o medicamento (@Model.NomeMedicamento)?</h3>
</div>

<a class="btn btn-primary" role="button" asp-controller="Medicamento" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger" role="button" asp-controller="Medicamento" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

Views/Medicamento/Criar.cshtml
@model MedicamentoModel
@{
    ViewData["Title"] = "Criar Medicamento";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Medicamento</h1>

</div>

<form asp-controller="Medicamento" asp-action="Criar" method="post">
    <div class="mb-3">
        <label for="nomeMedicamento" class="form-label">Nome</label>
        <input type="text" asp-for="NomeMedicamento" class="form-control" placeholder="Nome do Medicamento">
        @Html.ValidationMessageFor(x => x.NomeMedicamento)
    </div>
    <div class="mb-3">
        <label for="DataFabricacao" class="form-label">Data de Fabricação</label>
        <input type="date" asp-for="DataFabricacao" class="form-control" placeholder="Data de Fabricação do Medicamento">
        @Html.ValidationMessageFor(x => x.DataFabricacao)
    </div>
    <div class="mb-3">
        <label for="dataValdiade" class="form-label">Data de Validade</label>
        <input type="date" asp-for="DataVencimento" class="form-control" placeholder="Data de Validade do Medicamento">
        @Html.ValidationMessageFor(x => x.DataVencimento)
    </div>
    <div class="mb-3">
        <label for="descricao" class="form-label">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Descrição do Medicamento">
        @Html.ValidationMessageFor(x => x.Descricao)
    </div>

    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Medicamento" asp-action="Index" role="button">Voltar</a>
</form>

Views/Medicamento/Editar.cshtml
@model MedicamentoModel

@{
    ViewData["Title"] = "Editar Medicamento";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Medicamento</h1>

</div>

@* asp-route-id="@Model.Id" *@

<form asp-controller="Medicamento" asp-action="Alterar" asp-route-id="@Model.Id" method="post">

    <input type="hidden" asp-for="Id"/>

    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="NomeMedicamento" class="form-control" placeholder="Nome do Medicamento">
        @Html.ValidationMessageFor(x => x.NomeMedicamento)
    </div>
    <div class="mb-3">
        <label for="dataFabricacao" class="form-label">Data de Fabricação</label>
        <input type="date" asp-for="DataFabricacao" class="form-control" placeholder="Data de Fabricação do Medicamento">
        @Html.ValidationMessageFor(x => x.DataFabricacao)
    </div>
    <div class="mb-3">
        <label for="dataValdiade" class="form-label">Data de Validade</label>
        <input type="date" asp-for="DataVencimento" class="form-control" placeholder="Data de Validade do Medicamento">
        @Html.ValidationMessageFor(x => x.DataVencimento)
    </div>
    <div class="mb-3">
        <label for="descricao" class="form-label">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Descrição do Medicamento">
        @Html.ValidationMessageFor(x => x.Descricao)
    </div>

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Medicamento" asp-action="Index" role="button">Voltar</a>
</form>

Views/Medicamento/Index.cshtml
@model List<MedicamentoModel>

@{
    ViewData["Title"] = "Controle de Medicamentos";
}

<div class="text-center">

    
    <h1 class="display-4">Listagem de Medicamentos</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Medicamento" asp-action="Criar">Adicionar novo medicamento</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] is not null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] is not null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <table class="table" id="talbe-medicamentos">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome Medicamento</th>
                <th scope="col">Data Fabricação</th>
                <th scope="col">Data de Validade</th>
                <th scope="col">Descrição</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            
                @if(Model != null && Model.Any())
                {
                    foreach (var medicamento in Model)
                    {
                        <tr>
                            <th scope="row">@medicamento.Id</th>
                            <td>@medicamento.NomeMedicamento</td>
                            <td>@medicamento.DataFabricacao</td>
                            <td>@medicamento.DataVencimento</td>
                            <td>@medicamento.Descricao</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a role="button" class="btn btn-primary" asp-route-id="@medicamento.Id" asp-controller="Medicamento" asp-action="Editar">Editar</a>
                                    <a role="button" class="btn btn-secondary" asp-route-id="@medicamento.Id" asp-controller="Medicamento" asp-action="ApagarConfirmacao">Apagar</a>
                                </div>
                            </td>
                        </tr>
                    }
                } 
        </tbody>
    </table>
</div>